name: SecureStack Secrets Analysis
on:
    push:
        branches:
        - main
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run SecureStack Secrets Analysis
          uses: SecureStackCo/actions-secrets@v0.1.3
          with:
              # SecureStack API key - generate one at https://app.securestack.com
              securestack_api_key:
              # SecureStack Application ID - available when viewing applications at https://app.securestack.com
              securestack_app_id:
              # Severities lower than this input value will not be reported; value should be one of: critical | high | medium | low
              severity:
              # Optional flags for the bloodhound-cli secrets command - run bloodhound-cli code --help for more details.
              flags: -x
          
